### ISSUE TITLE
Write an "unzipping" function that can be called on in image_encoder function

### ISSUE THREAD

**Issue by sputney13** [EricaSkerrett/bme590final#19]
corresponds with note in lines 92-94 of final.py

image_encoder could have an if statement: if image_format is .zip, then run through unzipping function, then run each image through image_encoder successively

**Comment by EricaSkerrett** [comment]
Do you know what "rb" is referencing?https://github.com/EricaSkerrett/bme590final/blob/1c13f96c1b64697abdeb4326f5a5f54f6eff8c62/final.py#L94
