### ISSUE TITLE
Write unit tests for image_encoder and view_b64_image

### ISSUE THREAD

**Issue by sputney13** [EricaSkerrett/bme590final#23]
currently passing via assert 1 == 1

**Comment by EricaSkerrett** [comment]
@suyashkumar @mlp6 
Hi! To unit test the encoders, I'm currently working on uploading a test_images folder to git. The unit test would then open an image from this folder to run through the code. However, checking the output of this requires super long strings...Would you recommend testing with really compressed image files, spending time looking into generating an image file within the unit test itself, or another option? 
Thank you!

**Comment by mlp6** [comment]
Can you just check the first few and last few characters in the encoded data?

**Comment by EricaSkerrett** [comment]
Yep! Makes sense. I guess that + the length should be pretty foolproof.

**Comment by EricaSkerrett** [comment]
Do you think there would be a problem with including the test_images folder?

**Comment by mlp6** [comment]
Nope, as long as it is small.
