### ISSUE TITLE
Outline image processing functions

### ISSUE THREAD

**Issue by EricaSkerrett** [EricaSkerrett/bme590final#3]
Create flow diagram of functions

**Comment by EricaSkerrett** [comment]
Review of possible functions:

**1. Histogram equalization** 

-  `from skimage import exposure`
-  `skimage.exposure.equalize_hist(image_array)`  
- returns float array
- may need to import image as float? or data.image()?
- can maybe run unit test to check if array has full span for contrast? Or at least a larger range than the original array. 

**2. Contrast stretching/Normalization/Histogram stretching**

- `exposure.rescale_intensity(image, in_range=(#, #))`
- unit test by make sure range of array is as expected

**3. Log Compression**

- Maybeee `skimage.exposure.adjust_log(image, gain=0.#)`
- Input: image ndarray
- Output: logarithm corrected output image
- (Need to double check that this does what I want)

**4. Reverse Video**

- May need to manually reverse frames, or find another API

**5. Up2Us?**

- [http://scikit-image.org/docs/stable/auto_examples/index.html](url)

**Comment by EricaSkerrett** [comment]
@mlp6  Hi Dr. Palmeri, Suyash mentioned that "reverse video" doesn't have to do with a video file (and may mean inverting the image?) Would you please be able to clarify what functionality/processing technique you're looking for there? Thank you!

**Comment by mlp6** [comment]
https://dukecolab.slack.com/archives/C8S5A3TN1/p1524183844000233?thread_ts=1524183844.000233&cid=C8S5A3TN1
