### ISSUE TITLE
Error message during local pep 8 checking. 

### ISSUE THREAD

**Issue by RoujiaW** [EricaSkerrett/bme590final#34]
I got an error message when I try to run pytest-pep 8 locally but it seems like travis on github doesn't have any problems. I am wondering what might be the reason? Is there anything not compatible?

_______________________________________________________________________________ ERROR collecting test_final.py _______________________________________________________________________________
ImportError while importing test module '/Users/rosesharpaywang/Desktop/BME590Palmeri/bme590final/test_final.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
test_final.py:2: in <module>
    import final
final.py:7: in <module>
    from matplotlib import pyplot as plt
.venv/lib/python3.6/site-packages/matplotlib/pyplot.py:2374: in <module>
    switch_backend(rcParams["backend"])
.venv/lib/python3.6/site-packages/matplotlib/pyplot.py:207: in switch_backend
    backend_mod = importlib.import_module(backend_name)
/anaconda3/lib/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
.venv/lib/python3.6/site-packages/matplotlib/backends/backend_macosx.py:14: in <module>
    from matplotlib.backends import _macosx
**E   ImportError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are using (Ana)Conda please install python.app and replace the use of 'python' with 'pythonw'. See 'Working with Matplotlib on OSX' in the Matplotlib FAQ for more information.**

**Comment by mlp6** [comment]
I think you are hitting this issue: https://matplotlib.org/faq/osx_framework.html

**Comment by EricaSkerrett** [comment]
@RoujiaW which file is this in reference to? Maybe I can download it and test it on my machine?

**Comment by RoujiaW** [comment]
> @RoujiaW which file is this in reference to? Maybe I can download it and test it on my machine?

Erica, my pep-8 checking always return me error on test_final.py and final.py locally, while travis is fine with both files

**Comment by RoujiaW** [comment]
get away with this by only checking individual files

**Comment by mlp6** [comment]
You can use a `setup.cfg` file to ignore the `test*.py` files rather than having to individually include other `*.py` files.

**Comment by RoujiaW** [comment]
@mlp6 Thank you so much for this input! This will save me a lot of time
