### ISSUE TITLE
Menu button in GUI

### ISSUE THREAD

**Issue by RoujiaW** [EricaSkerrett/bme590final#35]
I need some helps adding menu options based on this tutorial https://pythonspot.com/pyqt5-menu/.

**Comment by EricaSkerrett** [comment]
Alrighty. Do you need me to map out which buttons we'll need, make the code for it, or troubleshoot something? @RoujiaW

**Comment by RoujiaW** [comment]
Do you want to first install PyQT on your laptop? It takes a very long time. The demo code below doesn't work for me. 
`mainMenu = self.menuBar() 
fileMenu = mainMenu.addMenu('File')
editMenu = mainMenu.addMenu('Edit')
viewMenu = mainMenu.addMenu('View')
searchMenu = mainMenu.addMenu('Search')
toolsMenu = mainMenu.addMenu('Tools')
helpMenu = mainMenu.addMenu('Help')`

**Comment by RoujiaW** [comment]
@EricaSkerrett let me rethink about this. We may not need the menu buttons. Let us talk about this in class. I will bring an outline

**Comment by RoujiaW** [comment]
Based on Tuesday's discussion. We won't need menu buttons.
