### ISSUE TITLE
Outline GUI components

### ISSUE THREAD

**Issue by RoujiaW** [EricaSkerrett/bme590final#36]

**Comment by RoujiaW** [comment]
**- GUI Window:** 
(This part won't have interactions with server.py)
1.  Welcome Page
2. Title
3. Author 

**- User Sign In/Sign Up:**
1. Textbox to input username
2. Button 1: create a new user
_which post request? What exceptions to catch?_

3. Button 2: look at existing user
_which get request? What exceptions to catch?_

**- Upload Image:**
1. File Dialog -- choose an image/images/zip file from your computer
2. Upload Button:
_which encode functions? What exceptions to catch?_: input the file names
_which post request? What exceptions to catch?_: post to database
_which get request? What exceptions to catch?_

3. View Upload Images:
_which get request? What exceptions to catch?_


3. Display Original Image(s)

**- Process Image:**
1. button for each processing request:
_which post request? What exceptions to catch?_

2. Display processed images, histogram image size, timestamps, user actions: 
_which get request? what exceptions to catch?_

3. Download processed images from previous get request:
_which decoder functions? what exceptions to catch?_

**- Return to the menu: or Upload new image(s)**

**Comment by RoujiaW** [comment]
@EricaSkerrett @sputney13 Could you guys let me know the post/get requests, expected inputs and outputs, and exceptions those requests will raise.

**Comment by sputney13** [comment]
For User Sign-In buttons 1 and 2, see pull request #38

**Comment by RoujiaW** [comment]
@EricaSkerrett @sputney13 I will need helps to complete the questions I had in the first comments. It will be super helpful, if you can link to the code and edit my first comment directly!

**Comment by sputney13** [comment]
@RoujiaW 
Checkout the updates I made to your comment above, I think you should have all the client functions necessary to have the required info for your buttons. I said this in a pull request, but it is a good idea to call on the client function directly and just plug in your inputs. I have already imported client and done that for the user buttons just so that the code is a little less confusing

**Comment by RoujiaW** [comment]
@sputney13 That sounds great! I can try that. Sometimes I need to modify it a bit to fit in the GUI. Maybe I can modify on the client.py?
