### ISSUE TITLE
Virtualenv and Matplotlib Import Error

### ISSUE THREAD

**Issue by RoujiaW** [EricaSkerrett/bme590final#60]
Hi @suyashkumar, I know you are more familiar with OS X system. I always encounter this import error because of ImportError: Python is not installed as a framework. I read the instructions given by https://matplotlib.org/faq/osx_framework.html. I tried stdlib's venv first and it didn't work as expected. Then there seems like another way that: "If you absolutely need to use virtualenv rather than venv, then from within the environment you can set the PYTHONHOME environment variable to $VIRTUAL_ENV, then invoke Python using the full path to the framework build (typically /usr/local/bin/python)." Could you give me a bit more hint on how to achieve this?

**Comment by suyashkumar** [comment]
@RoujiaW Give this a shot, bit of a wild card...
```python
import matplotlib  
matplotlib.use('TkAgg')   
import matplotlib.pyplot as plt 
```
in the first place you use matplotlib.


 it seems like they're asking you to do the following:
```
export PYTHONHOME=$VIRTUAL_ENV
/usr/local/bin/python YOUR_SCRIPT.py
```
That's a bit cumbersome though...
