### ISSUE TITLE
Check if code is robust for other image formats

### ISSUE THREAD

**Issue by EricaSkerrett** [EricaSkerrett/bme590final#67]

**Comment by sputney13** [comment]
Just a note, I tested it with a (legit) .png file (not capy2.png which is secretly a .jpg). It worked fine with that. Not sure about a .tiff, or a .zip of files.

(Speaking of .zip files, I did put a line in the code that requires the images extracted from them to be .jpg, .tiff, or .png. If they aren't, it just deletes them, lmao).

**Comment by sputney13** [comment]
I think we have a sufficient handle on this by now
