### ISSUE TITLE
Problem with storing encoded image outlined in #68

### ISSUE THREAD

**Issue by sputney13** [EricaSkerrett/bme590final#69]
See #68 for full description:

Our image encoder outputs a base64 string but when this output is saved to the database it is instead saved as binary.

When attempting to re-encode the binary extracted from the database, it again outputs a base64 string but I receive an error message that says I am trying to save bytes into a JSON. Is this an issue with the encoder, or something else?

(The full error message and references to the lines of code causing the problem are in pull request #68, I didn't want to merge the pull request in case I had broken something)

**Comment by mlp6** [comment]
Can you post a permalink for the line where the database entry is saved?  (Trying to search for it hasn't proven fruitful...)

**Comment by sputney13** [comment]
https://github.com/EricaSkerrett/bme590final/blob/beefa498a35ad3bc76096e8b03417d3f3e38d9ae/final.py#L208

The function including this line (I think you might have found it on the pull request)
